name: motherest
favicon: null
layout_spectrum: 0.34764
typography_spectrum: 0.28185534104704857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#301b22'
    - '#59a8eb'
    - '#7a5159'
    - '#bf8583'
    - '#f2c8ce'
  brandStrength: 0.1875
  lightness: 0.9497844730503857
  saturation: 0.75
  rhythmicContrast: 0.35490345349535346
purpose: []
